spring:
  datasource:
    url: jdbc:mysql://198.18.41.101:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
